
server:
  port: 9999
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/product?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useAffectedRows=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 2
      max-active: 10
      initial-size: 4
      max-wait: 600
      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。
      # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      validation-query: SELECT 1
      # 申请连接时执行validationQuery检测连接是否有效 默认为true
      test-on-borrow: true
      # 归还连接时执行validationQuery检测连接是否有效 默认为false
      test-on-return: false
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.220.141:8848
        namespace: 549f72eb-6390-4e62-8ad6-39422f8390fc

#seata配置
seata:
  # 1.0新特性，需要依赖seata-spring-boot-starter,默认为true
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: seataGroup-${seata.application-id}
  service:
    vgroup-mapping: default
    #配置Client连接TC的地址
    grouplist: 47.106.220.141:8091
    # 是否禁用全局事务
    disable-global-transaction: false
  config:
    type: file
    file:
      name: file.conf
  registry:
    type: nacos
    nacos:
      cluster: default
      server-addr: 47.106.220.141:8848

mybatis:
  mapper-locations: classpath:sqlclient/*.xml
  type-aliases-package: cn.chenw.commonservice.model

logging:
  level:
    root: info
